apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: twitter-crawl
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawl
            image: eu.gcr.io/cogniflare-rd/twitter-crawl:v1.1.0
          restartPolicy: OnFailure
